# Generated by Django 2.2 on 2021-12-01 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('review', models.CharField(max_length=5000)),
                ('rating', models.IntegerField()),
                ('category', models.CharField(max_length=200)),
                ('image', models.ImageField(default='images/none/noimg.jpg', upload_to='images')),
                ('description', models.CharField(max_length=5000)),
            ],
        ),
    ]
